<template>
  <section class="section blog-single mt-5">
    <div class="container">
      <div class="row">
        <div class="col-md-10 m-auto mb-5">

          <article class="single-post text-center">
            <h1>{{ pageData.title }}</h1>
            <h3>{{ pageData.subtitle }}</h3>
          </article>

          <p class="text-white"><strong>{{ pageData.description }} </strong></p>

          <p>
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your
            information when You use the Service and tells You about Your privacy rights and how the law protects You.
            We use Your Personal data to provide and improve the Service. 
          </p>
          <p>
            By using the Service, You agree to the
            collection and use of information in accordance with this Privacy Policy. 
          </p>
          <h4 class="mt-5">Interpretation and Definitions</h4>
          <p>
            The words of which the initial letter is capitalized have meanings defined under the following conditions. The
            following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
          </p>
          <h4 class="mt-5">Definitions</h4>

          <p>For the purposes of this Privacy Policy:</p>

          <ul>
            <li>
              Account means a unique account created for You to access our Service or parts of our Service.
            </li>
            <li>
              Affiliate means an entity that controls, is controlled by or is under common control with a party, where
              "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote
              for election of directors or other managing authority.
            </li>
            <li>
              Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to HackGuardia.
            </li>
            <li>
              Cookies are small files that are placed on Your computer, mobile device or any other device by a website,
              containing the details of Your browsing history on that website among its many uses.
            </li>
            <li>
              Country refers to: Florida, United States
            </li>
            <li>
              Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.
            </li>
            <li>
              Personal Data is any information that relates to an identified or identifiable individual.
            </li>
            <li>
              Service refers to the Website.
            </li>
            <li>
              Service Provider means any natural or legal person who processes the data on behalf of the Company. It
              refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide
              the Service on behalf of the Company, to perform services related to the Service or to assist the Company in
              analyzing how the Service is used.
            </li>
            <li>
              Usage Data refers to data collected automatically, either generated by the use of the Service or from the
              Service infrastructure itself (for example, the duration of a page visit).
            </li>
            <li>
              Website refers to HackGuardia, accessible from http://hackguardia.com
            </li>
            <li>
              You means the individual accessing or using the Service, or the company, or other legal entity on behalf of
              which such individual is accessing or using the Service, as applicable.
            </li>
          </ul>

          <h5>Collecting and Using Your Personal Data</h5>

          <p>
            While using Our Service, We may ask You to provide Us with certain personally identifiable information that
            can be used to contact or identify You. Personally identifiable information may include, but is not limited
            to email address and usage data
          </p>
          <p>
            We will not share or sell your personal information to any third party. We will use your information to
            contact you if there is information you need to know to continue to use our service.
          </p>
          <h5>Usage Data</h5>
          <p>
            Usage Data is collected automatically when using the Service.
          </p>
          <p>
            Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser
            type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time
            spent on those pages, unique device identifiers and other diagnostic data.
          </p>
          <p>
            When You access the Service by or through a mobile device, We may collect certain information automatically,
            including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address
            of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique
            device identifiers and other diagnostic data. We may also collect information that Your browser sends whenever
            You visit our Service or when You access the
            Service by or through a mobile device.
          </p>
          <h5>Cookies</h5>
          <p>
            We use Cookies and similar tracking technologies to track the activity on Our Service and store certain
            information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to
            improve and analyze Our Service. The technologies We use may include Cookies or Browser Cookies. A cookie is a
            small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a
            Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our
            Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use
            Cookies
          </p>
          <h5>Legal Requirements</h5>
          <ul>
            <li>
              To comply with a legal obligation
            </li>
            <li>
              To protect and defend the rights or property of the Company
            </li>
            <li>
              To prevent or investigate possible wrongdoing in connection with the Service
            </li>
            <li>
              To protect the personal safety of Users of the Service or the public
            </li>
            <li>
              To protect against legal liability
            </li>
          </ul>
          <h5> Children's Privacy</h5>
          <p>
            Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable
            information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child
            has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data
            from anyone under the age of 13 without verification of parental consent, We take steps to remove that
            information from Our servers.
          </p>
          <h5>Links to Other Websites</h5>
          <p>
            Our Service may contain links to other websites that are not operated by Us. If You click on a third party
            link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of
            every site You visit.
          </p>
          <p>
            We have no control over and assume no responsibility for the content, privacy policies or practices of any
            third party sites or services.
          </p>
          <h5>Changes to this Privacy Policy</h5>
          <p>
            We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new
            Privacy Policy on this page.
          </p>
          <p>
            We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming
            effective and update the "Last updated" date at the top of this Privacy Policy.
          </p>
          <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy
            are effective when they are posted on this page.
          </p>
          <h5>Contact Us</h5>
          <p>If you have any questions about this Privacy Policy, You can contact us by email: questions@hackguardia.com</p>
        </div>
      </div>
    </div>
  </section>
</template>
<script setup>
import { ref } from 'vue'
const pageData = ref(
  {
    title: 'Privay Policy',
    subtitle: 'The HackGuardia Privacy Policy',
    description: 'Last updated: February 28, 2024',
    // image: '/images/personal-privacy.webp',
    // imageAlt: 'Personal Privacy',
  }
)
</script>

<style scoped>h1 {
  margin: 0;
  padding: 0;
}

h3 {
  margin: 0 0 1rem 0 !important;
  padding: 0 !important;
}

h5 {
  margin: 3rem 0 1rem 0 !important;
  padding: 0 !important;
}
li{
  margin: 0 0 .33rem 0 !important;
  padding: 0 !important;
}
</style>